### ISSUE TITLE
Empty crossreferences being generated

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-plugin-glossarist#30]
From https://github.com/metanorma/metanorma/issues/75

In processing TC 211, I am finding several instances of a source being empty:

````
[.source]
<<,>>
````

This is of course illegal in Metanorma, and reflects an error in processing references.

The instances in TC 211 are all the second source mentioned for a term, which makes me suspect that they may be boundary issues of some sort.

This is what the first such instance looks like as generated Asciidoc:

````
==== data quality value unit


value unit for reporting a data quality result


[example]
"metre"





[NOTE]
====
A data quality value unit is provided only when applicable for a data quality result.
====





[.source]
<<ISO_19113_2002,4.13>>


[.source]
<<,>>
````

I think this is generated out of: isotc211-glossary/geolexica/localized-concept/47ca5126-8b31-5d2a-ba0e-2d55054273de.yaml

````
---
data:
  dates:
  - date: 2002-12-01 00:00:00.000000000 +05:00
    type: accepted
  - date: 2013-12-15 00:00:00.000000000 +05:00
    type: amended
  definition: []
  examples:
  - content: '"metre"'
  id: '121'
  notes:
  - content: A data quality value unit is provided only when applicable for a data
      quality result.
  release: -1.0
  sources:
  - origin:
      ref: ISO 19113:2002
      clause: '4.13'
      link: https://www.iso.org/standard/26018.html
    type: authoritative
    status: unspecified
  - origin:
      ref: ''
    type: lineage
  terms:
  - type: expression
    designation: Einheit der Datenqualitätsangabe
  language_code: deu
  entry_status: retired
  review_date: 2013-12-15 00:00:00.000000000 +05:00
  review_decision_date: 2013-12-15 00:00:00.000000000 +05:00
  review_decision_event: Publication of ISO 19157:2013
dateAccepted: 2002-12-01 00:00:00.000000000 +05:00
id: 47ca5126-8b31-5d2a-ba0e-2d55054273de
status: retired
````

If `sources.origin.ref` is empty, then the `[.source]` should simply be suppressed from output.
